/** @type {import('tailwindcss').Config} */
// Ported from the AtmosIQ Stitch export (Material 3 tokens).
// Neutral surface/text families use CSS variables so the dark toggle works;
// brand + semantic colors are the exact Stitch hex values.
const v = (name) => `rgb(var(${name}) / <alpha-value>)`

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // neutrals (theme-swappable)
        background: v('--c-background'),
        surface: v('--c-surface'),
        'surface-bright': v('--c-surface-bright'),
        'surface-dim': v('--c-surface-dim'),
        'surface-container-lowest': v('--c-sc-lowest'),
        'surface-container-low': v('--c-sc-low'),
        'surface-container': v('--c-sc'),
        'surface-container-high': v('--c-sc-high'),
        'surface-container-highest': v('--c-sc-highest'),
        'surface-variant': v('--c-surface-variant'),
        'on-surface': v('--c-on-surface'),
        'on-surface-variant': v('--c-on-surface-variant'),
        'on-background': v('--c-on-background'),
        outline: v('--c-outline'),
        'outline-variant': v('--c-outline-variant'),
        'inverse-surface': v('--c-inverse-surface'),
        'inverse-on-surface': v('--c-inverse-on-surface'),
        'surface-tint': v('--c-surface-tint'),
        // brand + semantic (fixed)
        primary: '#00685f',
        'on-primary': '#ffffff',
        'primary-container': '#008378',
        'on-primary-container': '#f4fffc',
        'inverse-primary': '#6bd8cb',
        'primary-fixed': '#89f5e7',
        'primary-fixed-dim': '#6bd8cb',
        'on-primary-fixed': '#00201d',
        'on-primary-fixed-variant': '#005049',
        secondary: '#006c49',
        'on-secondary': '#ffffff',
        'secondary-container': '#6cf8bb',
        'on-secondary-container': '#00714d',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        tertiary: '#825100',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#a36700',
        'on-tertiary-container': '#fffbff',
        'tertiary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      borderRadius: { DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', '2xl': '1rem', '3xl': '1.5rem', full: '9999px' },
      spacing: {
        'gutter-desktop': '1.5rem', 'space-xl': '2rem', 'margin-tablet': '2rem', 'space-md': '1rem',
        'margin-desktop': '3rem', 'space-lg': '1.5rem', 'gutter-mobile': '1rem', 'space-sm': '0.75rem',
        'space-2xs': '0.25rem', 'space-xs': '0.5rem', 'space-3xl': '4rem', 'space-2xl': '3rem', 'margin-mobile': '1rem',
      },
      fontFamily: {
        'body-md': ['Plus Jakarta Sans', 'sans-serif'], 'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'metric-stat': ['Plus Jakarta Sans', 'sans-serif'], 'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
        title: ['Plus Jakarta Sans', 'sans-serif'], 'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'], 'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'], 'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'sans-serif'], 'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        sans: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['1rem', { lineHeight: '1.5rem', letterSpacing: '0em', fontWeight: '400' }],
        'headline-lg': ['2.25rem', { lineHeight: '2.75rem', letterSpacing: '-0.025em', fontWeight: '700' }],
        'metric-stat': ['2.5rem', { lineHeight: '2.75rem', letterSpacing: '-0.03em', fontWeight: '800' }],
        'label-sm': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.02em', fontWeight: '600' }],
        title: ['1.125rem', { lineHeight: '1.6rem', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['0.875rem', { lineHeight: '1.35rem', letterSpacing: '0em', fontWeight: '400' }],
        'headline-md': ['1.5rem', { lineHeight: '2rem', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-sm': ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-lg-mobile': ['1.75rem', { lineHeight: '2.25rem', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.01em', fontWeight: '600' }],
        display: ['3rem', { lineHeight: '3.5rem', letterSpacing: '-0.03em', fontWeight: '700' }],
        'body-lg': ['1.125rem', { lineHeight: '1.75rem', letterSpacing: '-0.005em', fontWeight: '400' }],
      },
      maxWidth: { '7xl': '80rem' },
    },
  },
  plugins: [],
}
